recovery-builder/config/routes.rb
Rails.application.routes.draw do

  root 'application#home'
  get  '/unauthorized' => 'application#unauthorized'

  resources :users do
    resources :highlights, only:[:show, :index, :new, :create]
  end

  resources :highlights, only:[:show, :index]
  resources :completions, only:[:create]

  resources :houses, only:[:new,:create,:index,:show] do
    resources :highlights, only:[:index]
  end
  resources :goals, only:[:new, :create, :show, :index]

  get '/auth/github', :as=> 'github_auth'
  match 'auth/github/callback' => 'sessions#create', :via => [:get, :post]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'unassigned' => 'users#unassigned'
  get '/mentors' => 'users#mentors'
  get '/users/:id/bio'=> 'users#bio'

end

recovery-builder/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecoveryBuilder</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/lux/bootstrap.min.css">

  <%= stylesheet_link_tag    'application'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

<div class = "show errors">
  <% if flash[:message]%>
<%=flash[:message]%>
<%end%>

</div>
<br>
<br>
<br>

<div class="footer">
  <%=link_to "See All House Mentors", mentors_path, class:"navbar-brand", method:"get"%>

  <p>  <%=link_to "Home", user_path(session[:user_id]), class:"navbar-brand"%>
    <%=link_to "Sign Out", logout_path, class:"navbar-brand", method:"delete"%>
    </p>
</div>

</body>
</html>

recovery-builder/app/views/layouts/root_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecoveryBuilder</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/lux/bootstrap.min.css">

  <%= stylesheet_link_tag    'application'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
  <div class=" show" role="navigation">
        <div class="container">
          <div class="navbar-header">


          <%=link_to "Create New Account", new_user_path, class:"navbar-brand"%>
          <%=link_to "Login", '/login', class:"navbar-brand"%><br>
          OR <br>
          <%=link_to "Sign In With Github", github_auth_path, class: "navbar-brand"%>
          </div>


</body>
</html>

recovery-builder/app/views/layouts/sessions_layout.html.erb
<!DOCTYPE html>
<html>
<html>
<head>
  <title>RecoveryBuilder</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/lux/bootstrap.min.css">

  <%= stylesheet_link_tag    'application'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
  <body>


    <div class="footer">
      <%=link_to "Home", root_path, class:"navbar-brand"%>
    </div>
  </body>
</html>