recovery-builder/config/routes.rb
Rails.application.routes.draw do

  root 'application#home'
  get  '/unauthorized' => 'application#unauthorized'

  resources :users do
    resources :highlights, only:[:show, :index, :new, :create]
  end

  resources :highlights, only:[:show, :index]
  resources :completions, only:[:create]

  resources :houses, only:[:new,:create,:index,:show] do
    resources :highlights, only:[:index]
  end
  resources :goals, only:[:new, :create, :show, :index]

  get '/auth/github', :as=> 'github_auth'
  match 'auth/github/callback' => 'sessions#create', :via => [:get, :post]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'unassigned' => 'users#unassigned'
  get '/mentors' => 'users#mentors'
  get '/users/:id/bio'=> 'users#bio'

end

recovery-builder/app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :name, :presence => true
  validates :point_value, :presence => true
  belongs_to :house
  has_many :completions
  has_many :users, through: :completions
  end

recovery-builder/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :is_manager
  skip_before_action :is_manager, only:[:show, :index]

  def new
    if current_user.house_id.nil?
      flash[:notice] = "You must belong to a house before you can create goals"
      redirect_to edit_user_path(session[:user_id])
    else
    @goal = Goal.new
  end
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.save
    flash[:message] = "New Goal Has Been Added"
    redirect_to house_path(@goal.house_id)
end

  def show
    @goal = Goal.find(params[:id])
    @completion = @goal.completions.build(user_id: session[:user_id])
  end

  def index
    @goals  = current_user.house.goals
  end


  private

  def goal_params
    params.require(:goal).permit(:name, :point_value, :house_id)
  end

end

recovery-builder/app/views/goals/index.html.erb
<h1>Current Goals Available For Your House</h1>
<br>

<%@goals.each do |g|%>
<p><%=link_to g.name, goal_path(g)%></p>
<%end%>

recovery-builder/app/views/goals/new.html.erb
<h1>Set new Goals</h1>
<%=form_for @goal do |f|%>
<%=f.label :name%>
<%=f.text_field :name%>
<%=f.label :point_value%>
<%=f.text_field :point_value%>
<%=f.hidden_field :house_id, value: current_user_house.id%>
<br>
<br>
<%=f.submit%>
<%end%>

recovery-builder/app/views/goals/show.html.erb
<div class= "show">
<h1><%=@goal.name%></h1>
<h2>This Goal is worth <%=@goal.point_value%> points</h2>
<br>
<%=form_for @completion do |f|%>
<%=f.hidden_field :user_id%>
<%=f.hidden_field :goal_id%>
<%=f.hidden_field :completed, value: true%>
<%=f.submit "Complete This Goal"%>
<%end%></div>