recovery-builder/config/routes.rb
Rails.application.routes.draw do

  root 'application#home'
  get  '/unauthorized' => 'application#unauthorized'

  resources :users do
    resources :highlights, only:[:show, :index, :new, :create]
  end

  resources :highlights, only:[:show, :index]
  resources :completions, only:[:create]

  resources :houses, only:[:new,:create,:index,:show] do
    resources :highlights, only:[:index]
  end
  resources :goals, only:[:new, :create, :show, :index]

  get '/auth/github', :as=> 'github_auth'
  match 'auth/github/callback' => 'sessions#create', :via => [:get, :post]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'unassigned' => 'users#unassigned'
  get '/mentors' => 'users#mentors'
  get '/users/:id/bio'=> 'users#bio'

end

recovery-builder/app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :presence => true
  validates  :name, :uniqueness => true
  has_secure_password
  belongs_to :house
  has_many :completions
  has_many :goals, through: :completions
  has_many :highlights


  def self.mentors
    mentors_array = []
    self.all.each do |m|
      if m.employed == true && m.points > 100
        mentors_array << m.name
      end
    end
    self.where(name:mentors_array).order(points: :desc)
  end

  def self.employed
    self.where(employed: true)
  end

  def self.ordered_by_points
    self.order(points: :desc)
  end

  def self.house_not_assigned
    self.where(house_id: nil)
  end

  def omni
      self.password_digest ||= user.password_digest = SecureRandom.hex
      self.name = auth[:info][:name]
      self.save
    end


end

recovery-builder/app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :is_manager, only:[:edit]
skip_before_action :authentication_required, only:[:new, :create]
layout 'root_layout', except:[:show, :edit, :unassigned, :bio]

  def new
    @houses = House.all
    @user = User.new
  end

  def create

    @houses = House.all
    @user = User.new(user_params)
    if @user.save
    session[:user_id] = @user.id
    redirect_to user_path(@user)
    else
    render :new
    end
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html {render :show}
      format.json { render json: @user}
      end
  end

  def edit
    @houses = House.all
    @user = User.find(params[:id])
    @user.save
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    @user.save
    redirect_to user_path(@user)
  end

  def unassigned
    @unassigned_users = User.house_not_assigned
  end

  def mentors
    @mentors = User.mentors
    respond_to do |f|
      f.html{render layout: 'sessions_layout'}
      f.json {render :json=> @mentors}
    end
    #render layout: 'sessions_layout'
  end

  def destroy
    @user = User.find(params[:id]).destroy
    redirect_to house_path(current_user)
  end

  def bio
    #raise params.inspect
    @user = User.find(params[:id])
  end



  private

  def user_params
    params.require(:user).permit(:name, :password, :manager, :house_id, :bio)
  end

end

recovery-builder/app/helpers/users_helper.rb
module UsersHelper

def check_errors
  if !@user.errors.blank?
    @user.errors.full_messages.first
  end
end

def current_user_house
  current_user.house
end

def this_current_user(user)
  current_user == user
  end

  def correct_view(user)
    current_user_house && this_current_user(user)
  end


end

recovery-builder/app/views/users/_form.html.erb
<div class="errors">
    <%if !@user.errors.blank?%>
  <%=@user.errors.full_messages.first%>
    <%elsif flash[:notice]%>
  <%=flash[:notice]%>
  <%end%></div>
  <br>
  <%=form_for @user do |f|%>
  <p><%=f.label :name%>
  <%=f.text_field :name%></p>
  <%=f.label "Choose a House"%>
    <%if @user.house%>
    <%=collection_select(:user, :house_id, @houses, :id, :name, prompt: "Select House" , selected: @user.house.id)%>
    <%else%>
    <%=collection_select(:user, :house_id, @houses, :id, :name, prompt: "Select House")%>
    <%end%>
  <p><%=f.label "Check here if you are a Manager"%>
 <%=f.check_box :manager%></p>
 <p>Please add a short bio</p>
  <%=f.text_area :bio%><br><br>
  <p><%=f.label :password %>
  <%=f.password_field :password, value: :password%></p>
  <p><%=f.submit%></p>
  <%end%>
</div>

recovery-builder/app/views/users/bio.html.erb
<div class="show">
<h1 id="username"><%=@user.name%><br></h1>


<h3><p id="userbio"><%=@user.bio%><%=@user.bio%><p></h3>
<a href="#" id="next" data-id="<%=@user.id%>">View Next Resident Bio</a>

</div>

recovery-builder/app/views/users/edit.html.erb
<h1>Edit Resident</h1>

<%=render 'form'%>

<%=link_to "Delete User", @user , class:"navbar-brand", method:"delete"%>

recovery-builder/app/views/users/mentors.html.erb
<div class="show">
  <h1>All House Mentors</h1><br><br><br>

  Mentor status is a great achievement! To become a House Mentor, a resident needs to accumulate 100 points as well as find empoyment.
  As a House Mentor you are no longer subject to curfew and are expected to hold yourself accountable and look out for new guys that come
  into the program.
  <div id="mentors">

  </div>

  <a href="/mentors" class="mentors">Load List Of All Mentors</a>
</div

recovery-builder/app/views/users/new.html.erb
<h1>Sign Up </h1>
<%=render 'form'%>

recovery-builder/app/views/users/show.html.erb
<div class="show">
  <h1><%=@user.name%></h1>
  <%=check_errors%>
  <br>
  <%if !@user.manager%>
  <h1>Currently Has <%=@user.points%> Points</h1>
  <%else%>
  <h1>House Manager</h1>
  <%end%>
  <%if @user.house%>
  <h3>Belongs To <%=@user.house.name%> House</h3>
  <%else%>
  <h3>You have not been assigned to a house yet.</h3>
  <%end%>
  <br>
  <div class="alert alert-dismissible alert-danger">


    <%if current_user.manager%>
    <%=link_to 'Create a new house', new_house_path%>
    <p><%=link_to 'Create New Goals', new_goal_path%></p>
    <p><%= link_to 'Assign New Resident Houses', unassigned_path%></p>
    <p><%=link_to "Update User Account", edit_user_path(@user)%></p>

    <%else%>
    <%=link_to "Gain Some Recovery Points!", goals_path if correct_view(@user)%>
    <%end%>
    <p><%=link_to "View Highlights for #{@user.name}", user_highlights_path(@user)%></p>
    <p><%=link_to "Submit Daily Highlight", new_user_highlight_path(current_user) if this_current_user(@user)%></p>
    <p><%= link_to "View All Highlights", highlights_path%></p>
    <p id="user"><%=link_to "View Your House", house_path(current_user.house_id) if correct_view(@user)%></p>



    <a href="/users/<%=@user.id%>/bio">View Bio Page </a>

  </div>


</div>

recovery-builder/app/views/users/unassigned.html.erb
<div class= "show">
<h1>These Residents Still Need To Be Assigned A House</h1>

<br>
<br>

<%@unassigned_users.each do |u|%>
<h3><%=link_to u.name, edit_user_path(u)%></h3>
<%end%>
</div>